# Generated by Django 6.1.1 on 2026-09-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileInfo',
        ),
        migrations.AlterModelTable(
            name='profileinfo',
            table='profiles_info',
        ),
    ]
