# Generated by Django 6.1.1 on 2026-09-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_profile_profileinfo_alter_profileinfo_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
