# Generated by Django 6.1.1 on 2026-09-11 08:53

import django.db.models.deletion
import django.utils.timezone
import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0002_branch_admin_email_branch_admin_first_name_and_more'),
        ('masterbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', shared.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('total_copies', models.IntegerField(default=0)),
                ('shelf_category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='branch.branch')),
                ('master_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_books', to='masterbook.masterbook')),
            ],
            options={
                'db_table': 'book',
                'ordering': ['-created_at'],
                'unique_together': {('master_book', 'branch')},
            },
        ),
    ]
