# Generated by Django 6.1.1 on 2026-09-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='copy_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
