# Generated by Django 6.1.1 on 2026-09-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmasterbook',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='masterbook',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='historicalmasterbook',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='masterbook',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
