# Generated by Django 6.1.1 on 2026-09-11 11:12

import django.db.models.deletion
import django.utils.timezone
import shared.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', shared.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('copy_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
                ('condition_notes', models.CharField(blank=True, max_length=255)),
                ('is_delete', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='book.book')),
            ],
            options={
                'db_table': 'book_copy',
                'ordering': ['copy_code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBookCopy',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', shared.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('copy_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('issued', 'Issued'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('retired', 'Retired')], default='available', max_length=20)),
                ('condition_notes', models.CharField(blank=True, max_length=255)),
                ('is_delete', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='book.book')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical book copy',
                'verbose_name_plural': 'historical book copys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
